name: Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version:
          - v0.10.4
          - stable
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Install Lua 5.1
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.1.5"
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v6
      - name: Install nlua
        run: luarocks install nlua
      - name: Install busted
        run: luarocks install busted
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1.6.1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Run tests with busted
        run: busted
